"""Build runtime WebP sprite strips from compressed transparent frames.

Reads each action's transparent_frames_webp/*.webp, normalizes every frame to
a shared canvas (body-height aligned, centered), composes one horizontal strip,
and emits src/client/pet-action-sheets.generated.ts with WebP data URIs.

Playback speed: derived from source frame counts to stay smooth (the earlier
AI-generated sheets used 100-160ms; the H3 clips are 24fps ~3s, so we sample
an even subset of frames and play at a natural cadence).
"""
from pathlib import Path
import base64
import io
import json

import numpy as np
from PIL import Image

ROOT = Path(r"H:\ds\dsh-token-pet")
ACTION_ROOT = ROOT / "Review/h3-actions"
OUT_TS = ROOT / "src/client/pet-action-sheets.generated.ts"

TARGET_H = 320          # character body height inside each cell
FRAME_W = 240
FRAME_H = 360
# Per-action playback delay (ms). H3 clips run ~3s of motion; playing 8 sampled
# frames at these delays keeps the motion readable without feeling laggy.
DELAYS = {
    "idle": 160,
    "working": 140,
    "eating": 140,
    "digesting": 150,
    "warning": 130,
    "evolve": 130,
    "click": 110,
    "archive": 150,
    "tool-success": 120,
    "tool-failure": 140,
    "prompt-enhancing": 140,
    "prompt-ready": 130,
}
# Looping actions repeat; the rest play once and return to idle.
LOOPS = {
    "idle": True, "working": True, "warning": True, "prompt-enhancing": True,
    "eating": False, "digesting": False, "evolve": False, "click": False,
    "archive": False, "tool-success": False, "tool-failure": False,
    "prompt-ready": False,
}
# Frame sampling: H3 renders 32 frames (~3s); 8 evenly spaced frames carry the
# motion at the delays above. idle keeps all 32 for a smooth breathing loop.
SAMPLE = 8

ACTIONS = sorted(LOOPS.keys())


def sample_frames(paths, count):
    if len(paths) <= count:
        return paths
    idxs = [round(i * (len(paths) - 1) / (count - 1)) for i in range(count)]
    seen, picked = set(), []
    for i in idxs:
        if i not in seen:
            seen.add(i)
            picked.append(paths[i])
    return picked


def build_action(action):
    webp_dir = ACTION_ROOT / action / "transparent_frames_webp"
    paths = sorted(webp_dir.glob("matte_*.webp"))
    if not paths:
        raise SystemExit(f"no webp frames for {action}")
    chosen = sample_frames(paths, len(paths) if action == "idle" else SAMPLE)
    frames = [Image.open(p).convert("RGBA") for p in chosen]

    # Union alpha bbox (character region) across sampled frames.
    boxes = []
    for f in frames:
        a = np.array(f)[:, :, 3]
        ys, xs = np.where(a > 16)
        if len(xs) == 0:
            continue
        boxes.append((int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1))
    ux0 = min(b[0] for b in boxes); uy0 = min(b[1] for b in boxes)
    ux1 = max(b[2] for b in boxes); uy1 = max(b[3] for b in boxes)
    scale = TARGET_H / (uy1 - uy0)
    cw = round((ux1 - ux0) * scale)
    ch = round((uy1 - uy0) * scale)
    if cw > FRAME_W:
        k = FRAME_W / cw
        cw, ch = FRAME_W, round(ch * k)
        scale *= k
    strip = Image.new("RGBA", (FRAME_W * len(frames), FRAME_H), (0, 0, 0, 0))
    ox = (FRAME_W - cw) // 2
    oy = (FRAME_H - ch) // 2
    for i, f in enumerate(frames):
        crop = f.crop((ux0, uy0, ux1, uy1)).resize((cw, ch), Image.Resampling.LANCZOS)
        strip.alpha_composite(crop, (i * FRAME_W + ox, oy))
    buf = io.BytesIO()
    strip.save(buf, "WEBP", quality=90, method=6)
    return {
        "action": action,
        "frames": len(frames),
        "b64": base64.b64encode(buf.getvalue()).decode("ascii"),
        "webpKB": len(buf.getvalue()) // 1024,
        "delay": DELAYS[action],
        "loop": LOOPS[action],
    }


def main():
    entries, total_kb = [], 0
    for action in ACTIONS:
        e = build_action(action)
        total_kb += e["webpKB"]
        entries.append(e)
        print(f"{action}: {e['frames']} frames, {e['webpKB']} KB strip", flush=True)

    lines = [
        "// Generated by scripts/build-runtime-webp-sheets.py — do not edit by hand.\n",
        "// Frames: H3 U10 I2VA v09 clips, chroma-keyed, compressed to WebP q90.\n\n",
        "export interface ActionSheetSpec {\n",
        "  sheet: string; frameW: number; frameH: number; bodyHeight: number; frames: number;\n",
        "  delaysMs: number[]; loop: boolean; totalMs: number;\n",
        "}\n\n",
        "export const PET_ACTION_SHEET_SPECS: Record<string, ActionSheetSpec> = {\n",
    ]
    for e in entries:
        delays = json.dumps([e["delay"]] * e["frames"], separators=(",", ":"))
        lines += [
            f"  '{e['action']}': {{\n",
            f"    sheet: 'data:image/webp;base64,{e['b64']}',\n",
            f"    frameW: {FRAME_W},\n",
            f"    frameH: {FRAME_H},\n",
            f"    bodyHeight: {TARGET_H},\n",
            f"    frames: {e['frames']},\n",
            f"    delaysMs: {delays},\n",
            f"    loop: {str(e['loop']).lower()},\n",
            f"    totalMs: {e['delay'] * e['frames']},\n",
            "  },\n",
        ]
    lines.append("}\n")
    OUT_TS.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT_TS} ({OUT_TS.stat().st_size // 1024} KB; strips total {total_kb} KB)", flush=True)


if __name__ == "__main__":
    main()
