from pathlib import Path
import base64
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/qpet/identity/qpet-stage-01-newborn-v02-resident.png"
TARGET = ROOT / "assets/pet/qpet-resident.png"
TS_TARGET = ROOT / "src/client/pet-asset.generated.ts"

image = Image.open(SOURCE).convert("RGBA")
# The approved source uses a near-uniform cream studio background. Flood-fill
# only pixels connected to the canvas edge so pale details inside the character
# remain intact.
for seed in ((0, 0), (image.width - 1, 0), (0, image.height - 1), (image.width - 1, image.height - 1)):
    ImageDraw.floodfill(image, seed, (0, 0, 0, 0), thresh=34)

alpha = image.getchannel("A")
bbox = alpha.getbbox()
if bbox is None:
    raise RuntimeError("background removal produced an empty image")
left, top, right, bottom = bbox
padding = 18
crop = image.crop((max(0, left - padding), max(0, top - padding), min(image.width, right + padding), min(image.height, bottom + padding)))
# A compact Web asset is enough for the 64–320 px floating pet range.
crop.thumbnail((512, 512), Image.Resampling.LANCZOS)
TARGET.parent.mkdir(parents=True, exist_ok=True)
crop.save(TARGET, format="PNG", optimize=True)
encoded = base64.b64encode(TARGET.read_bytes()).decode("ascii")
TS_TARGET.write_text(
    "// Generated by scripts/prepare-pet-asset.py; do not edit by hand.\n"
    f"export const FORMAL_PET_ASSET = 'data:image/png;base64,{encoded}'\n",
    encoding="utf-8",
)
print(f"wrote {TARGET} ({crop.width}x{crop.height}) and {TS_TARGET}")
